hyperwallet/php-sdk

- CHANGELOG.md
- src/Hyperwallet/Hyperwallet.php
- src/Hyperwallet/Model/BankCard.php
- src/Hyperwallet/Model/BankCardStatusTransition.php
- src/Hyperwallet/Model/PaperCheck.php
- src/Hyperwallet/Model/PaperCheckStatusTransition.php
- src/Hyperwallet/Model/PaymentStatusTransition.php
- src/Hyperwallet/Model/UserStatusTransition.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
- tests/Hyperwallet/Tests/Model/BankCardStatusTransitionTest.php
- tests/Hyperwallet/Tests/Model/BankCardTest.php
- tests/Hyperwallet/Tests/Model/ModelTestCase.php
- tests/Hyperwallet/Tests/Model/PaperCheckTest.php
Extend with absent endpoints (Band Card, Paper Check etc.)
> Extend with absent endpoints (Band Card, Paper Check etc.)

- src/Hyperwallet/Model/BankCard.php
https://jira.site1.hyperwallet.local/browse/HW-48915
> HW-48915 add cvv field to the sdk-php

- src/Hyperwallet/Model/BankAccount.php
- src/Hyperwallet/Model/PaperCheck.php
- src/Hyperwallet/Model/TransferMethod.php
https://jira.site1.hyperwallet.local/browse/HW-54847
> HW-54847 Remove Relationship field from Server SDK

- src/Hyperwallet/Model/BankAccount.php
- src/Hyperwallet/Model/PaperCheck.php
- src/Hyperwallet/Model/TransferMethod.php
- src/Hyperwallet/Model/User.php
https://jira.site1.hyperwallet.local/browse/HW-57518
> Add Business Operating Name Field to User - PHP

- examples/three-step-tutorial.php
- src/Hyperwallet/Hyperwallet.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
https://jira.site1.hyperwallet.local/browse/HW-53780
> Fixed incorrect Server address.

- src/Hyperwallet/Hyperwallet.php
- src/Hyperwallet/Model/PayPalAccountStatusTransition.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
https://jira.site1.hyperwallet.local/browse/HW-51699
> Add PayPal Account Status Transitions - PHP

- src/Hyperwallet/Exception/HyperwalletApiException.php
- src/Hyperwallet/Util/ApiClient.php
- tests/Hyperwallet/Tests/Util/ApiClientTest.php
https://jira.site1.hyperwallet.local/browse/HW-51701
> Null Pointer Exception on getMessage

- src/Hyperwallet/Hyperwallet.php
- src/Hyperwallet/Response/ListResponse.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
Removed 'links' attribute for V4 Balances.
> Removed 'links' attribute for V4 Balances

- .travis.yml
- src/Hyperwallet/Hyperwallet.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
> added transfer methods

- src/Hyperwallet/Hyperwallet.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
- tests/Hyperwallet/Tests/Util/HyperwalletEncryptionTest.php
Added missed get and list TransferStatusTransition methods in PHP-V3.
> Added missed get and list TransferStatusTransition methods in PHP-V3

- .travis.yml
- src/Hyperwallet/Hyperwallet.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
Added missed get and list TransferStatusTransition methods in PHP-V4.
> Added missed get and list TransferStatusTransition methods in PHP-V4

- src/Hyperwallet/Hyperwallet.php
- src/Hyperwallet/Model/BusinessStakeholderStatusTransition.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
Added Business Stakeholder related methods to PHP-V4.
> Added Business Stakeholder related methods to PHP-V4

- src/Hyperwallet/Util/ApiClient.php
- src/Hyperwallet/Util/HyperwalletUUID.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
- tests/Hyperwallet/Tests/Util/ApiClientTest.php
- tests/Hyperwallet/Tests/Util/HyperwalletUUIDTest.php
Please review the changes and approve.
> Added V4 headers for sdk-type, sdk-version and sdk-contextId

- src/Hyperwallet/Hyperwallet.php
- tests/Hyperwallet/Tests/Util/HyperwalletEncryptionTest.php
Hi
I am back-porting these merged PRs (which were merged into v4), so that they can also be in v3 api sdk version.
https://github.com/hyperwallet/php-sdk/pull/44/files
https://github.com/hyperwallet/php-sdk/pull/23/files
Could you please accept and tag this in v1 of this SDK?
Thanks!
> Backporting changes merged to v4, also in v3

- src/Hyperwallet/Model/User.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
JIRA Ticket: https://engineering.paypalcorp.com/jira/browse/DTPAYWONE-564
- Added taxVerificationStatus property, getter and setter, and constants for allowed values to User.php.
- Added setting and checking of taxVerificationStatus to testCreateUser_withProgramTokenInUserObject in HyperwalletTest.php.
> DTPAYWONE-564: Add taxVerificationStatus to User class

- CHANGELOG.md
- src/Hyperwallet/Util/ApiClient.php
Ticket: https://engineering.paypalcorp.com/jira/browse/DTONBWTWO-503
Changes made:
- Added unlisted changes to change log
- Changed version from 2.1.1 -> 2.2.0
> modified change log and version of sdk to 2.2.0

- CHANGELOG.md
- src/Hyperwallet/Model/User.php
- src/Hyperwallet/Util/ApiClient.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
Ticket: https://engineering.paypalcorp.com/jira/browse/DTPAYWONE-588
Added taxVerificationStatus to user and relevant tests
> added taxVerificationStatus to user and tests

- CHANGELOG.md
https://engineering.paypalcorp.com/jira/browse/DTONBWTWO-503
Added to changelog to reflect recently committed change
> edited changlog to reflect recent commit

- CHANGELOG.md
- src/Hyperwallet/Util/ApiClient.php
Ticket: https://engineering.paypalcorp.com/jira/browse/PPPLMER-105096
> changes for release 2.2.1

- CHANGELOG.md
- src/Hyperwallet/Util/ApiClient.php
Ticket: https://engineering.paypalcorp.com/jira/browse/PPPLMER-105096
> changes for release 1.7.1

- .travis.yml
- composer.json
- src/Hyperwallet/Util/ApiClient.php
- src/Hyperwallet/Util/HyperwalletEncryption.php
- src/Hyperwallet/Util/HyperwalletUUID.php
For Guzzle 7 / Laravel 8 - reference #73 #89
> [V4] Support guzzle 7 - #73

- .travis.yml
- composer.json
- src/Hyperwallet/Util/ApiClient.php
- src/Hyperwallet/Util/HyperwalletEncryption.php
- src/Hyperwallet/Util/HyperwalletUUID.php
For Guzzle 7 / Laravel 8 - reference #73 #89
> [V3] Support for guzzle 7 - Issue #73

- CHANGELOG.md
- README.md
Update change logs and readme for 1.7.2 release 
Unit test result:
> feature/DTSERWONE-1083 - Prepare SDK V3 for 1.7.2 release

- CHANGELOG.md
> feature/DTSERWONE-1083 - Prepare SDK V3 for 2.2.2 release

- .github/workflows/ci.yml
- composer.json
- phpunit.xml.dist
- src/Hyperwallet/Exception/HyperwalletApiException.php
- src/Hyperwallet/Exception/HyperwalletArgumentException.php
- src/Hyperwallet/Exception/HyperwalletException.php
- src/Hyperwallet/Model/HyperwalletVerificationDocument.php
- src/Hyperwallet/Model/HyperwalletVerificationDocumentReason.php
- src/Hyperwallet/Util/ApiClient.php
- src/Hyperwallet/Util/HyperwalletUUID.php
- src/Hyperwallet/Util/HyperwalletUriTemplate.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
- tests/Hyperwallet/Tests/Model/BaseModelTest.php
- tests/Hyperwallet/Tests/Model/ModelTestCase.php
- tests/Hyperwallet/Tests/Response/ErrorResponseTest.php
- tests/Hyperwallet/Tests/Response/ListResponseTest.php
- tests/Hyperwallet/Tests/Util/ApiClientTest.php
- tests/Hyperwallet/Tests/Util/HyperwalletEncryptionTest.php
- tests/Hyperwallet/Tests/Util/HyperwalletUUIDTest.php
- tests/Hyperwallet/Tests/Util/HyperwalletUriTemplateTest.php
Enhanced the PHP-SDK to support PHP version build from 5.6 to 8.1
- Introduce Hyperwallet URI Template 
- Introduce GitHubAction to test PHP version from 5.6 to latest 
- Address PHP Unit test compatibility
PHPUnit test result
https://github.com/grmeyer-hw-dev/php-sdk/actions/runs/2921584056
> feature/DTSERWONE-1083 - V4 Support php versions

- .github/workflows/ci.yml
- src/Hyperwallet/Exception/HyperwalletApiException.php
- src/Hyperwallet/Hyperwallet.php
- src/Hyperwallet/Model/BaseModel.php
- src/Hyperwallet/Model/BusinessStakeholder.php
- src/Hyperwallet/Model/PrepaidCard.php
- src/Hyperwallet/Model/TransferRefund.php
- src/Hyperwallet/Response/ErrorResponse.php
- src/Hyperwallet/Response/ListResponse.php
- src/Hyperwallet/Util/ApiClient.php
- src/Hyperwallet/Util/HyperwalletEncryption.php
- tests/Hyperwallet/Tests/HyperwalletTest.php
- tests/Hyperwallet/Tests/Model/ClientTokenTest.php
Address documentation issues pointed by PHPStun 
Continuation from https://github.com/hyperwallet/php-sdk/pull/119
> [Investigation] [WIP] [Part-2] feature/DTSERWONE-1083 - PHP 8.1 - Address Documentation issue 

- .github/workflows/documentation.yml
- apigen.neon
Introduce PHP Api Documentation
- Introduce ApiGen tool to build the PHP-SDK doc
- Push the updated documentation to gh-pages branch
- Trigger GitHub Action only on merging PR on master
https://github.com/hyperwallet/php-sdk/issues/107
Api Doc link: https://hyperwallet.github.io/php-sdk
> DTSERWONE-846 - Introduce Github action to generate API DOC
